---
title: "R Notebook"
output: html_notebook
---

# 2 Names and values

```{r libaries, message=FALSE, include=FALSE}

# install.packages("lobstr")
library(lobstr)

```

## 2.2 Binding basics

```{r BBintro}

x <- c(1, 2, 3)
y <- x

obj_addr(x)
obj_addr(y)

obj_addr(x)== obj_addr(y)

```

```{r non-syntact}

`_abc` <- 1
`_abc`

`if` <- 10
`if`

```


```{r BBexec1}

a <- 1:10
b <- a
c <- b
d <- 1:10

obj_addr(a) == obj_addr(b)
obj_addr(b) == obj_addr(c) 
obj_addr(c) != obj_addr(d) 

```

```{r BBexec2}

obj_addr(mean)
obj_addr(base::mean)
obj_addr(get("mean"))
obj_addr(evalq(mean))
obj_addr(match.fun("mean"))
obj_addr(match.fun(`mean`))

```

```{r BBexec4}

?make.names

```

## 2.3 Copy-on-modify

```{r COMintro}

x <- c(1, 2, 3)
y <- x

obj_addr(x)== obj_addr(y)


y[[3]] <- 4
x
y

obj_addr(x)== obj_addr(y)


```

```{r tracemem}

x <- c(1, 2, 3)
cat("x:", tracemem(x), "\n")

y <- x
cat("y:", tracemem(y), "\n")
cat("\n")

y[[3]] <- 4L
y[[3]] <- 5L

untracemem(c(x, y))

```

```{r funtionCalls}

f <- function(a) {
  a
}

x <- c(1, 2, 3)
cat("x:", tracemem(x), "\n")

z <- f(x)

obj_addr(x) == obj_addr(z)

untracemem(x)

```

```{r lists}

l1 <- list(1, 2, 3)
l2 <- l1

cat("l2: ",tracemem(l2))
l2[[3]] <- 4
cat("\n")

ref(l1, l2)

```

```{r DFs}

d1 <- data.frame(x = c(1, 5, 6), y = c(2, 4, 3))
d2 <- d1
d2[, 2] <- d2[, 2] * 2
d3 <- d1
d3[1, ] <- d3[1, ] * 3

ref(d1)
cat("\n")
ref(d2)
cat("\n")
ref(d3)

```

```{r charVec}

x <- c("a", "a", "abc", "d")
ref(x, character = TRUE)

```

```{r COMexec1}

cat("(1:10): ",tracemem(1:10))

```

```{r COMexec2}

x <- c(1L, 2L, 3L)
cat("x: ",tracemem(x))

x[[3]] <- 4

```

```{r COMexec3}

a <- 1:10
b <- list(a, a)
c <- list(b, a, 1:10)

ref(a)
cat("\n")
ref(b)
cat("\n")
ref(c)

```

```{r COMexec4}

x <- list(1:10)
x[[2]] <- x

ref(x)

```

## 2.4 Object size

```{r OSintro}

obj_size(letters)
obj_size(ggplot2::diamonds)
cat("\n")

x <- runif(1e6)
obj_size(x)
y <- list(x, x, x)
obj_size(y)
cat("\n")

obj_size(list(NULL, NULL, NULL))
cat("\n")

banana <- "bananas bananas bananas"
obj_size(banana)
obj_size(rep(banana, 100))
cat("\n")

obj_size(x, y)
cat("\n")

obj_size(1:3)
obj_size(1:1e3)
obj_size(1:1e6)
obj_size(1:1e9)

```

```{r OSexec1}

y <- rep(list(runif(1e4)), 100)

object.size(y)
obj_size(y)

```

```{r OSexec2}

funs <- list(mean, sd, var)
obj_size(funs)

```

```{r OSexec3}

a <- runif(1e6)
obj_size(a)
cat("\n")

b <- list(a, a)
obj_size(b)
obj_size(a, b)
cat("\n")

b[[1]][[1]] <- 10
obj_size(b)
obj_size(a, b)
cat("\n")

b[[2]][[1]] <- 10
obj_size(b)
obj_size(a, b)

```

## 2.5 Modify-in-place

```{r singleBinding}


rm(list = ls(all.names = TRUE))
gc()
cat("\n")


v <- c(1, 2, 3)
cat("v: ", tracemem(v), "\n")

v[[3]] <- 4
cat("\n")

x <- data.frame(matrix(runif(5 * 1e4), ncol = 5))

medians <- vapply(x, median, numeric(1))
cat("x: ", tracemem(x), "\n")

for (i in seq_along(medians)) {
  x[[i]] <- x[[i]] - medians[[i]]
}
untracemem(x)
cat("\n")

y <- as.list(x)
cat("y: ", tracemem(y), "\n")

for (i in 1:5) {
  y[[i]] <- y[[i]] - medians[[i]]
}


```

```{r environments}

e1 <- rlang::env(a = 1, b = 2, c = 3)
e2 <- e1

e1$c <- 4
e2$c
cat("\n")

e <- rlang::env()
e$self <- e

ref(e)

```

```{r MIPexec1}

x <- list()
x[[1]] <- x

ref(x)

```

```{r MIPexec2}

# todo

```

```{r MIPexec3}

e1 <- rlang::env(a = 1, b = 2, c = 3)
tracemem(e1)

```



































































